### ISSUE TITLE
中间六边形的消失和11点钟方向六边形可见过渡的不够平滑

### ISSUE THREAD

**Issue by Clendy** [zjywill/OverwatchProgress#1]
守望玩的有段时间了，那个进度条科技感十足，作者这个做的非常不错，但感觉中间六边形的消失和11点钟方向六边形可见过程中，二者过渡的不够平滑

**Comment by zjywill** [comment]
增加动画循环的时间间隔，能稍微自然点，下一个动画不会来的太突然
